### ISSUE TITLE
Bug with pages merging

### ISSUE THREAD

**Issue by zverok** [molybdenum-99/mediawiktory#34]
``` ruby
w = MediaWiktory::Client.new('https://en.wikipedia.org/w/api.php')
res = w.query.generator(prefixsearch: {search: 'Guardians', limit: 100}).prop(revisions: {prop: :content}, info: {prop: :url}).redirects(true).perform
res.continue!
# ArgumentError: Unknown key in continued page: revisions
#      from /media/storage/work/gems/mediawiktory/lib/mediawiktory/page.rb:32:in `block in merge!'
```

If you look at raw structure: [page 1](https://en.wikipedia.org/w/api.php?action=query&generator=prefixsearch&gpssearch=Guardians&gpslimit=100&format=json&redirects=true&prop=revisions&rvprop=content), [page](https://en.wikipedia.org/w/api.php?action=query&generator=prefixsearch&gpssearch=Guardians&gpslimit=100&format=json&redirects=true&prop=revisions&rvprop=content&continue=||&rvcontinue=33938334|659375342) -- you'll notice some strange things, like one page is described as pageid+title, and its content is on continuation page. So, current merging algorithm is not sufficient.

**Comment by smostovoy** [comment]
After debugging I see that code fails on 'revisions' key and looking at json I see it's indeed present not on all pages.  So I'm not sure I understand what do you mean by "its content is on continuation page". http://screencast.com/t/dvArjcvUcv

**Comment by zverok** [comment]
The logic of MediaWiki is not clear to me currently. Look: 
[page 1](https://en.wikipedia.org/w/api.php?action=query&generator=prefixsearch&gpssearch=Guardians&gpslimit=100&format=json&redirects=true&prop=revisions&rvprop=content):

![](http://i.imgur.com/SU0m4us.png)

[page2](https://en.wikipedia.org/w/api.php?action=query&generator=prefixsearch&gpssearch=Guardians&gpslimit=100&format=json&redirects=true&prop=revisions&rvprop=content&continue=%7C%7C&rvcontinue=33938334%7C659375342): 

![](http://i.imgur.com/D1o0cdR.png)

It is data for same article (note the id), and trying to merge them, MediaWiktory will fail. 
For some articles it is vice versa: no data, only id on first page of query, and all article data on next pages.

It is strange, but it should work with MediaWiktory.

**Comment by intracer** [comment]
Yes, it's not guaranteed that one page data is returned in one response. You need to merge properties of next response by page id.
