### ISSUE TITLE
How to get specific section of Wiki page?

### ISSUE THREAD

**Issue by phlegx** [molybdenum-99/mediawiktory#36]
Hi!

I want to extract a specific section of a page. How can I do that? Thx for your help!

**Comment by zverok** [comment]
Basically, mediawiktory tries to reflect Wikipedia API, and you'll need to dig into its [docs](https://en.wikipedia.org/w/api.php) to do something interesting. The page content fetching is dubiously named "revisions", and all its options described [there](https://en.wikipedia.org/w/api.php?action=help&modules=query%2Brevisions), "fetch only one section" is `rvsection`. Having it translated to mediawiktory API, we can do something like:
```ruby

response = client.query.titles('Game_of_Thrones').prop(revisions: {prop: :content, section: '1'}).perform
puts response.pages.first.raw.revisions.first['*'] # prints source of "Plot" section
```

Some notes:
* this only can fetch top-level section (you can't say something like `section: '1.1'`);
* this literally fetches only one section from MediaWiki (not fetches entire pages & then extracts one section)
* section 0 is article intro.

**Comment by phlegx** [comment]
Hi @zverok, thank you! But the result is wikitext. How can I get the real html text?

**Comment by zverok** [comment]
Typically, API returns wikitext, and mediawiktory is API client. 
[Here](https://www.mediawiki.org/wiki/API:FAQ#get_the_content_of_a_page_.28HTML.29.3F) are some insights of what you can get and how.

**Comment by phlegx** [comment]
I have solved the problem as follow:

```ruby
# Get page with all sections
sections = client.parse.page('Game_of_Thrones').prop(:sections).perform
# Get section id
section = sections.raw.parse.sections.detect { |s| s.line == 'Inspirations and derivations' }[:index]
# Fetch specific section
response = client.parse.page('Game_of_Thrones').section(section).prop(:text).perform
# Get section content
response.raw.parse.text.values.first
```
